// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: test.proto

package bidirection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestGRPCClient is the client API for TestGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestGRPCClient interface {
	Send(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type testGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewTestGRPCClient(cc grpc.ClientConnInterface) TestGRPCClient {
	return &testGRPCClient{cc}
}

func (c *testGRPCClient) Send(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/test.TestGRPC/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestGRPCServer is the server API for TestGRPC service.
// All implementations should embed UnimplementedTestGRPCServer
// for forward compatibility
type TestGRPCServer interface {
	Send(context.Context, *Req) (*Res, error)
}

// UnimplementedTestGRPCServer should be embedded to have forward compatible implementations.
type UnimplementedTestGRPCServer struct {
}

func (UnimplementedTestGRPCServer) Send(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

// UnsafeTestGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestGRPCServer will
// result in compilation errors.
type UnsafeTestGRPCServer interface {
	mustEmbedUnimplementedTestGRPCServer()
}

func RegisterTestGRPCServer(s grpc.ServiceRegistrar, srv TestGRPCServer) {
	s.RegisterService(&TestGRPC_ServiceDesc, srv)
}

func _TestGRPC_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestGRPCServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TestGRPC/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestGRPCServer).Send(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// TestGRPC_ServiceDesc is the grpc.ServiceDesc for TestGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.TestGRPC",
	HandlerType: (*TestGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _TestGRPC_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
